version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /iap2/sidecar
    schedule:
      interval: weekly
    groups:
      cargo-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
