device_name: "Mira"
device_type: "car_thing"
log_level: "debug"

observer_mode: true

credentials:
  type: interactive

server:
  enabled: true
  address: "0.0.0.0"
  port: 3678
  allow_origin: "*"

report_url: "https://mira-reports.mira-thing.workers.dev/"

homeassistant:
  url: "http://10.10.1.104:8123"
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI0Mjg5YTRmMWQyZmU0NDMwYWI1YzdmYjBkZTFjMWQzNyIsImlhdCI6MTc4NjcxNzk2NSwiZXhwIjoyMTAyMDc3OTY1fQ.6MkEjuL8Km9fJnTx-Uwnl9AChwOlDf4h28Dd2tQ8HAI"

checkin: true
checkin_url: "https://mira-checkin.mira-thing.workers.dev"

voice:
  enabled: false
  wake: false
